name: starshmucks
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  persistent_bottom_nav_bar: ^5.0.2
  url_launcher: ^6.1.7
  sqflite: ^2.2.0+3
  path_provider: ^2.0.11
  dotted_line: ^3.1.0
  fluttertoast: ^8.1.2
  freerasp: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_size_text: ^3.0.0
  shared_preferences: ^2.0.15
  get: ^4.6.5
  email_auth: ^1.0.0
  provider: ^6.0.3
  email_validator: ^2.1.17
  google_fonts: ^3.0.1
  intl: ^0.18.0
  intl_phone_number_input: ^0.7.1
  flutter_bloc: ^8.1.1
  hexcolor:
  tbib_splash_screen: ^0.0.6
  flutter_lints: ^2.0.0
  razorpay_flutter: ^1.3.4
  upi_india: ^3.0.1
  image_picker: ^0.8.6
  scrollable_positioned_list: ^0.3.5

  dependencies:
  animated_check: ^1.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/shmucks.png"

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/cakes/
    - images/coffee/
    - json/
